const GraphQL = require('graphql');

const { 
	GraphQLObjectType, GraphQLString, GraphQLID, GraphQLInt 
} = GraphQL;

const UserType = new GraphQL.GraphQLObjectType({
	name: 'User',

	description: 'User type to manage all users in the app',

	fields: () => ({
		id: {
			type: GraphQLID,
			description: 'User ID auto generated by MongoDB'
		},
		name: {
			type: GraphQLString,
			description: 'User\'s full name'
		},
		email: {
			type: GraphQLString,
			description: 'User email; must be valid and unique'
		},
		phone: {
			type: GraphQLString,
			description: 'User phone number'
		},
		status: {
			type: GraphQLInt,
			description: 'User status: active or disabled'
		},
		created_at: {
			type: GraphQLString,
			description: 'Date and time account was created'
		},
		updated_at: {
			type: GraphQLID,
			description: 'Date and time account was last updated'
		}
	})
});

module.exports = UserType;